// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package lxc

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName     *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	SSHHost             *string           `mapstructure:"ssh_host" required:"true" cty:"ssh_host" hcl:"ssh_host"`
	SSHPort             *int              `mapstructure:"ssh_port" default:"22" cty:"ssh_port" hcl:"ssh_port"`
	SSHUser             *string           `mapstructure:"ssh_user" required:"true" cty:"ssh_user" hcl:"ssh_user"`
	SSHPassword         *string           `mapstructure:"ssh_password" cty:"ssh_password" hcl:"ssh_password"`
	SSHKeyPath          *string           `mapstructure:"ssh_key_path" cty:"ssh_key_path" hcl:"ssh_key_path"`
	Template            *string           `mapstructure:"template" required:"true" cty:"template" hcl:"template"`
	Storage             *string           `mapstructure:"storage" default:"local-lvm" cty:"storage" hcl:"storage"`
	Bridge              *string           `mapstructure:"bridge" default:"vmbr0" cty:"bridge" hcl:"bridge"`
	Memory              *int              `mapstructure:"memory" default:"2048" cty:"memory" hcl:"memory"`
	Cores               *int              `mapstructure:"cores" default:"2" cty:"cores" hcl:"cores"`
	RootPassword        *string           `mapstructure:"root_password" default:"changeme" cty:"root_password" hcl:"root_password"`
	Unprivileged        *bool             `mapstructure:"unprivileged" default:"true" cty:"unprivileged" hcl:"unprivileged"`
	Features            *string           `mapstructure:"features" default:"nesting=1" cty:"features" hcl:"features"`
	RootfsSize          *string           `mapstructure:"rootfs_size" default:"8" cty:"rootfs_size" hcl:"rootfs_size"`
	Vlan                *int              `mapstructure:"vlan" cty:"vlan" hcl:"vlan"`
	NetworkIP           *string           `mapstructure:"network_ip" default:"dhcp" cty:"network_ip" hcl:"network_ip"`
	Gateway             *string           `mapstructure:"gateway" cty:"gateway" hcl:"gateway"`
	Firewall            *bool             `mapstructure:"firewall" cty:"firewall" hcl:"firewall"`
	NetworkMTU          *int              `mapstructure:"network_mtu" cty:"network_mtu" hcl:"network_mtu"`
	BackupName          *string           `mapstructure:"backup_name" cty:"backup_name" hcl:"backup_name"`
	BackupDir           *string           `mapstructure:"backup_dir" default:"/var/lib/vz/template/cache" cty:"backup_dir" hcl:"backup_dir"`
	BackupMethod        *string           `mapstructure:"backup_method" default:"vzdump" cty:"backup_method" hcl:"backup_method"`
	BackupPigz          *int              `mapstructure:"backup_pigz" default:"1" cty:"backup_pigz" hcl:"backup_pigz"`
	CTID                *string           `mapstructure:"ctid" cty:"ctid" hcl:"ctid"`
	LXCConfig           *string           `mapstructure:"lxc_config" cty:"lxc_config" hcl:"lxc_config"`
	SSHTimeout          *string           `mapstructure:"ssh_timeout" default:"5m" cty:"ssh_timeout" hcl:"ssh_timeout"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"ssh_host":                   &hcldec.AttrSpec{Name: "ssh_host", Type: cty.String, Required: false},
		"ssh_port":                   &hcldec.AttrSpec{Name: "ssh_port", Type: cty.Number, Required: false},
		"ssh_user":                   &hcldec.AttrSpec{Name: "ssh_user", Type: cty.String, Required: false},
		"ssh_password":               &hcldec.AttrSpec{Name: "ssh_password", Type: cty.String, Required: false},
		"ssh_key_path":               &hcldec.AttrSpec{Name: "ssh_key_path", Type: cty.String, Required: false},
		"template":                   &hcldec.AttrSpec{Name: "template", Type: cty.String, Required: false},
		"storage":                    &hcldec.AttrSpec{Name: "storage", Type: cty.String, Required: false},
		"bridge":                     &hcldec.AttrSpec{Name: "bridge", Type: cty.String, Required: false},
		"memory":                     &hcldec.AttrSpec{Name: "memory", Type: cty.Number, Required: false},
		"cores":                      &hcldec.AttrSpec{Name: "cores", Type: cty.Number, Required: false},
		"root_password":              &hcldec.AttrSpec{Name: "root_password", Type: cty.String, Required: false},
		"unprivileged":               &hcldec.AttrSpec{Name: "unprivileged", Type: cty.Bool, Required: false},
		"features":                   &hcldec.AttrSpec{Name: "features", Type: cty.String, Required: false},
		"rootfs_size":                &hcldec.AttrSpec{Name: "rootfs_size", Type: cty.String, Required: false},
		"vlan":                       &hcldec.AttrSpec{Name: "vlan", Type: cty.Number, Required: false},
		"network_ip":                 &hcldec.AttrSpec{Name: "network_ip", Type: cty.String, Required: false},
		"gateway":                    &hcldec.AttrSpec{Name: "gateway", Type: cty.String, Required: false},
		"firewall":                   &hcldec.AttrSpec{Name: "firewall", Type: cty.Bool, Required: false},
		"network_mtu":                &hcldec.AttrSpec{Name: "network_mtu", Type: cty.Number, Required: false},
		"backup_name":                &hcldec.AttrSpec{Name: "backup_name", Type: cty.String, Required: false},
		"backup_dir":                 &hcldec.AttrSpec{Name: "backup_dir", Type: cty.String, Required: false},
		"backup_method":              &hcldec.AttrSpec{Name: "backup_method", Type: cty.String, Required: false},
		"backup_pigz":                &hcldec.AttrSpec{Name: "backup_pigz", Type: cty.Number, Required: false},
		"ctid":                       &hcldec.AttrSpec{Name: "ctid", Type: cty.String, Required: false},
		"lxc_config":                 &hcldec.AttrSpec{Name: "lxc_config", Type: cty.String, Required: false},
		"ssh_timeout":                &hcldec.AttrSpec{Name: "ssh_timeout", Type: cty.String, Required: false},
	}
	return s
}
